unit tests edited
Microflow-xyz/pokt-governance-pda-snapshot pull request #3
Opened 2024-01-11 14:39 UTC by satiparpar

Unit test edited and some new tests added.
The last method of the PDAService class ( getIssuedPDAs ) still needs more unit tests.
I will update it again ASAP.

2024-01-19 13:03 UTC, ahmadyazdanii requested changes
Thank you @satiparpar. First of all, You did it very well! Second, you could improve it and avoid repetition in your codes, but it's OK for now. You are on the right path. Keep going.

Please also append some other files' tests, which I mentioned in Discord. We need the coverage ratio to be above 85%.

2024-01-19 13:03 UTC, ahmadyazdanii commented on src/pda/tests/pda.service.spec.ts
> +      jest.spyOn(axios, 'post').mockReturnValue(of(axiosResponse));
You should spy on the `of` method of Rxjs lib

2024-01-25 11:50 UTC, ahmadyazdanii requested changes
Thank you @satiparpar 

You did your best, but some parts have some little mistakes. Please check the comments. Also, I recommend you watch the unit tests tutorial introduced to you on YouTube again. If you have any questions, I am available on Discord.

2024-01-25 11:50 UTC, ahmadyazdanii commented on src/common/arweave/__mocks__/arweave.provider.ts
> +  storeData: jest.fn(() => Promise.resolve('mockedTransactionId')),
For promise return values, jest has a built-in function which its name is [mockResolvedValue()](https://jestjs.io/docs/mock-function-api#mockfnmockresolvedvaluevalue). You can use that instead of `Promise.resolve()`

2024-01-25 11:50 UTC, ahmadyazdanii commented on src/pda/tests/pda.module.spec.ts
This file does not present only unit tests because you run some functions that have not ever been executed in this file. In this file, you should only check the metadata assigned to the exported class.

Also, it's not a necessary file to have unit tests because it does not contain any business logic.

2024-01-25 11:50 UTC, ahmadyazdanii commented on src/scoring/tests/scoring.module.spec.ts
This file does not present only unit tests because you run some functions that have not ever been executed in this file. In this file, you should only check the metadata assigned to the exported class.

Also, it's not a necessary file to have unit tests because it does not contain any business logic.

2024-01-25 11:50 UTC, ahmadyazdanii commented on src/scoring/__mocks__/scoring.service.ts
The mock does not cover all situations that could occur. And it's unnecessary in the scope because you only used that in the module(which you should avoid).

2024-01-25 11:50 UTC, ahmadyazdanii commented on src/scoring/tests/scoring.service.spec.ts
I just wanted to inform you that you did not write tests for 4 logging function calls in this file. You should do that. These lines in the file are 80,132,181,217

2024-01-25 11:50 UTC, ahmadyazdanii commented on src/tests/core.service.spec.ts
You did not test logic. Please look at the source file again and rewrite this test file.

2024-01-25 11:50 UTC, ahmadyazdanii commented on src/tests/main.spec.ts
This test does not cover nothings. Remove it or rewrite it in a better way.

2024-01-26 07:19 UTC, satiparpar commented on src/scoring/tests/scoring.module.spec.ts
OK. I will remove all *.module.spec.ts and focus on *.service.ts and improve unit tests

2024-01-26 07:21 UTC, satiparpar commented on src/scoring/__mocks__/scoring.service.ts
You are right! I will remove it.

2024-01-26 07:28 UTC, satiparpar commented on src/scoring/tests/scoring.service.spec.ts
I got them dude. Will cover them in the next commit. ;-)

2024-01-31 16:07 UTC, satiparpar commented
Hi again @ahmadyazdanii . I tried to consider your requests and apply them in my code. I tried to do my best.  I hope this code satisfies you.
Let me know if it needs any changes, I'm always ready to do more !

2024-02-11 09:20 UTC, ahmadyazdanii approved these changes

2024-02-11 09:21 UTC, merged